### PR TITLE
Add PSR16 adapter

### PR DESCRIPTION
**Pull request by jarstelfox**
This is needed for allow growthbook to use our memcache instance to back it's cache

### CODE REVIEW

**Review by djmetzle — APPROVED** [review]
LGTM CR :gear:

**Comment by jordycosta** [comment]
@jarstelfox Anything to QA here?

**Comment by djmetzle** [comment]
I found this integration test package for PSR-16 implementations that might be useful:
https://github.com/php-cache/integration-tests

**Comment by aburke07** [comment]
QA :alien: We have this hooked up in https://github.com/iFixit/ifixit/pull/54311 and we are correctly caching the features and then subsequently loading from the cache.

These is the logs from a page load with an experiment running:
image

**Comment by jarstelfox** [comment]
We might want to add the tests as it seems like a nice to have

**Pull request merged**
